name: "Build and publish release to Docker Hub"
on:
  release:
    types:
      - created

jobs:
  publish_release:
    name: publish_release
    runs-on: ubuntu-latest
    env:
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_IMAGE_APP: "dmitryapp/grammar-checker"

    steps:
      - name: Docker login
        run: docker login -u "${DOCKER_LOGIN}" -p "${DOCKER_PASSWORD}"

      - uses: actions/checkout@v3

      - name: Build APP image
        if: success()
        run: |
          docker pull ${DOCKER_IMAGE_APP} || true
          docker build --cache-from "${DOCKER_IMAGE_APP}:latest" --tag "${DOCKER_IMAGE_APP}:${{ github.event.release.tag_name }}" --target prod -f build/docker/nginx/Dockerfile .

      - name: Push DOCKER image
        if: success()
        run: |
          docker push "${DOCKER_IMAGE_APP}:${{ github.event.release.tag_name }}"
